---
# Perform source code compilation and installation nginx
# 2018-04-04 19:54 by liubaobao at WHKJ company

- name: Configure the build.
  command: ./configure
  args:
    chdir: /tmp/{{ WGET }}/

- name: Build Wget
  command: make
  args:
    chdir: /tmp/{{ WGET }}/

- name: Install Wget
  shell: make install
  args:
    chdir: /tmp/{{ WGET }}/
